spring.application.name=JavaContent_RAG

spring.config.import=optional:file:.env[.properties]

etl.pipeline.DataStorage.dataPath=${DATA_PATH}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
